<?php
require_once('config.php');
$link['INDEX']          = $config['site_url'];
$link['HOME']           = $config['site_url'] . 'home';
$link['LOGIN']          = $config['site_url'] . 'login';
$link['LOGOUT']         = $config['site_url'] . 'logout';
$link['SIGNUP']         = $config['site_url'] . 'signup';
$link['FORGOT']         = $config['site_url'] . 'forgot';
$link['DASHBOARD']      = $config['site_url'] . 'dashboard';
$link['BLOG']           = $config['site_url'] . 'blog';
$link['BLOG-SINGLE']    = $config['site_url'] . 'blog';
$link['BLOG-CAT']       = $config['site_url'] . 'blog/category';
$link['BLOG-AUTHOR']    = $config['site_url'] . 'blog/author';
$link['TESTIMONIALS']   = $config['site_url'] . 'testimonials';
$link['MEMBERSHIP']     = $config['site_url'] . 'membership';
$link['PAYMENT']        = $config['site_url'] . 'payment';
$link['IPN']            = $config['site_url'] . 'ipn';
$link['TRANSACTION']    = $config['site_url'] . 'transaction';
$link['ACCOUNT_SETTING'] = $config['site_url']. 'account-setting';
$link['FAQ']            = $config['site_url'] . 'faq';
$link['FEEDBACK']       = $config['site_url'] . 'feedback';
$link['REPORT']         = $config['site_url'] . 'report';
$link['HTML']           = $config['site_url'] . 'html';
$link['CONTACT']        = $config['site_url'] . 'contact';
$link['ADD_VCARD']      = $config['site_url'] . 'add-vcard';
$link['QRBUILDER']      = $config['site_url'] . 'qr-builder';
$link['INVOICE']        = $config['site_url'] . 'invoice';
$link['TEST']           = $config['site_url'] . 'test';